### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by forker11234** [bootleg/ret-sync#28]
There are exceptions when I trying to attach the windbg debugger to ida 7.4:

```[sync] set debugger dialect to windbg, enabling hotkeys
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 805, in cb_broker_on_out
    self.worker.parse_exec(req.strip())
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 596, in parse_exec
    req_handler(hash)
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 508, in req_set_dbg_dialect
    SyncForm.init_hotkeys()
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 1009, in init_hotkeys
    ('F2', self.broker.worker.bp_notice, 'BreakpointToggle'),
AttributeError: 'SyncForm_t' object has no attribute 'broker'```

and one more exception is thrown for some reason while debugging:
```Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 805, in cb_broker_on_out
    self.worker.parse_exec(req.strip())
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 599, in parse_exec
    req_handler(hash)
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 217, in req_loc
    self.hexsync.cb_loc(ea)
  File "C:/Program Files/IDA Pro 7.4/plugins\retsync\syncrays.py", line 99, in cb_loc
    func_ea = idaapi.get_func(ea).start_ea
AttributeError: 'NoneType' object has no attribute 'start_ea'```

**Comment by bootleg** [comment]
Hi forker11234, 

thank you for reporting the issues.

Could you give me some context about the first one ? Seems you tried to set a bp in IDA using the F2 shortcut and for some reason the broker was either not launched or has crashed (and its death not handled properly otherwise the shortcut should have been disable). Is there some relevant messages in the log window prior to the backtrace?

For the second one thhe issue looks more straightforward. Code in syncrays.py makes the assumption that a function is defined at current ea: https://github.com/bootleg/ret-sync/blob/347668fb5e0d53d39c8654d55ea8937e4834348a/ext_ida/retsync/syncrays.py#L99
 which may not be true. Is this analysis correct ? Were you trying to step code that was not defined as a function ?

Best regards,

**Comment by masterofpwn** [comment]
I'm hitting the exact same error (1st one).

```
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 805, in cb_broker_on_out
    for req in batch:
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 596, in parse_exec
    if type in ['broker', 'dialect', 'bc']:
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 508, in req_set_dbg_dialect
    rs_log("set debugger dialect to %s, enabling hotkeys" % dialect)
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 1009, in init_hotkeys
    ida_kernwin.update_action_shortcut(conflict, None)
AttributeError: 'SyncForm_t' object has no attribute 'broker'
```

I'm using kernel debugging, I have a breakpoint set in kd and the error is thrown when I execute !sync.

**Comment by masterofpwn** [comment]
Oh, I get this when executing !sync

```
[sync] sync update
[sync] failed to GetModuleByOffset for offset: 0xffffffff987384e2
```

I'm debugging a 32-bit kernel mode driver by the way (and using 32-bit kd and sync.dll).

**Comment by bootleg** [comment]
Hi @masterofpwn, 

thx for the additionnal input here. This one is giving me a hard time. Are the steps above reproducible?

```
[sync] sync update
[sync] failed to GetModuleByOffset for offset: 0xffffffff987384e2
```
The first line seems to indicate that sync was already enabled (thus the _update_). For some reason the debugger fails to resolve module for that specific offset. Is the offset 0x987384e2 correct btw ? 

Here I have an issue, I'd expect that the `!sync` command to doe nothing more and exit gently. This failure to resolve module would be unaccounted on the idb side though, which I should fix.

However from the stacktrace, `req_set_dbg_dialect` is only called for new debugger/client; which appears to contradict the first observation...

**Comment by masterofpwn** [comment]
This is actually embarrassing. I don't know what changed between yesterday, and today. I didn't notice this message before.

```
[sync] Warning, python.exe was detected but is installed as a Windows App (UWP).
       Dir: "C:\Users\bla\AppData\Local\Microsoft\WindowsApps\python.exe"
       This plugin requires a Windows desktop program in order to work properly.
       Searching for other installations.
```

And now when I try to run the plugin I get:

```
[sync] default idb name: sample.bin
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 1130, in OnCreate
    name = self.handle_name_aliasing()
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 1109, in handle_name_aliasing
    self.pdb_name_warning(name)
  File "C:/Program Files/IDA Pro 7.4/plugins/SyncPlugin.py", line 1071, in pdb_name_warning
    pdbpath = DbgDirHlpr.read_rsds_pdb()
TypeError: unbound method read_rsds_pdb() must be called with DbgDirHlpr instance as first argument (got nothing instead)
[sync] plugin loaded
```

Any idea?

**Comment by masterofpwn** [comment]
Probably doesn't help, but I went back to a version I download from this repo on Feb 10 and I don't see anymore errors in IDA.

```
[sync] default idb name: sample.bin
[sync] sync enabled
[sync] cmdline: "C:\Python27-x64\python.exe" -u "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py" --idb "sample_A.bin"
[sync] module base 0x0
[sync] hexrays #7.4.0.191011 found
[sync] broker started
[sync] plugin loaded
[sync] << broker << dispatcher not found, trying to run it
[sync] << broker << dispatcher now runs with pid: 18656
[sync] << broker << connected to dispatcher
[sync] << broker << listening on port 54269
[sync] set debugger dialect to windbg, enabling hotkeys
```

Note that I'm using the IDA plugin from Feb 10 and the sync.dll from 2 days ago. However I still get this at kd:

```
1: kd> .load sync
[sync] DebugExtensionInitialize, ExtensionApis loaded
1: kd> !sync
[sync] No argument found, using default host (127.0.0.1:9100)
[sync] sync success, sock 0x2c4
[sync] probing sync
[sync] sync is now enabled with host 127.0.0.1
1: kd> t
[sync] failed to GetModuleByOffset for offset: 0xffffffff987384e2
987384e2 6a60            push    60h
```

And yes, the address seems to be correct. Note that I rebased the file in IDA to 0x0 as you can see in the IDA's output from above.

**Comment by bootleg** [comment]
masterofpwn , regarding:

`[sync] failed to GetModuleByOffset for offset: 0xffffffff987384e2`

Is this a dynamically/manually loaded module (ie. not loaded by "_legitimate_" OS primitives) ? That would explain why `GetModuleByOffset `. If so you can use the `modmap ` to defined a synthetic (ie. _fake_) module with the name of your choice over that memory region and then be able to sync easily with you idb.

Thanks for the tip regarding the older version. The windbg extension has changed for a while. The issue seems to point to the new way shortcut are registered in IDA. I'll investigate that.

**Comment by bootleg** [comment]
Btw, I fixed the bug:
`TypeError: unbound method read_rsds_pdb() must be called with DbgDirHlpr instance as first argument (got nothing instead)`

Didn't catch it as I tested with Python3 (which would not raise the error). Python 2 and 3 behave differently.

**Comment by masterofpwn** [comment]
It's fixed indeed. Thanks.

The driver I'm using at the moment is loaded legitimately by the OS, and I "break" right at the beginning of a DriverEntry function. Which is when I try to load the extension. If I actually try to load it a little bit after I don't get anymore the error `failed to GetModuleByOffset`.

However, despite not having any errors none of the commands I enter in kd seem to be reflected in IDA. I'm currently connected...

```
1: kd> !idblist
> currently connected idb(s):
    [0] sample.bin
```

However, commands like `!lbl`, `!cmt`, `!bc on` are not showing in IDA. Might be something on my side, but can't really do much troubleshooting at the moment.

Thank you.

**Comment by masterofpwn** [comment]
The problem I had with `failed to GetModuleByOffset` was because at the time I was loading `sync` I hadn't done a `.reload /n`. After that it's sorted (your `modmap` tip I guess would have worked too).

However, I can't still see anything showing in IDA despite no errors in both sides.

Any tip so I can try to track the issue?
Thank you.

**Comment by masterofpwn** [comment]
Well, actually it works with other drivers. Don't why it doesn't with this specific one I've been working for the past couple of days. Sorry for the spam.

Thank you.

**Comment by bootleg** [comment]
Hey o/

Thank you for the feedback regarding `GetModuleByOffset`.

Now, regarding the syncing itself, my first intuition would be that the debugger identifies the module with a different name than your idb:

`[sync] cmdline: "C:\Python27-x64\python.exe" -u "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py" --idb "sample_A.bin"`

The dispatcher registers an entry with the name `sample_A.dll`. When the debuggers syncs, it connects to the dispatcher and sends a the name of its current module. If it matches an entry, then the idb becomes enabled.
You can either define an alias in the .sync file or use the field in the GUI to set a specific registering name for your idb.

**Comment by masterofpwn** [comment]
Oh, you're right! My bad. Thank you so much. Works like a charm!

**Comment by forker11234** [comment]
Hey, sorry for the delayed answer, I couldn't manage to reproduce the exception, but I'll write it when I will.
But there is another bug - I can't manage to make IDA and Windbg synchronized, I run windbg, connect it to the port ida generated, and from the windbg I get:
0:029> !sync
[sync] No argument found, using default host (127.0.0.1:25553)
[sync] sync success, sock 0x73c
[sync] probing sync
[sync] sync is now enabled with host 127.0.0.1

And IDA sometimes show the message [sync] set debugger dialect to windbg, enabling hotkeys and sometimes not, but anyway it doesn't sync with each other :< any idea why is this happening?

**Comment by bootleg** [comment]
Please see commit https://github.com/bootleg/ret-sync/commit/042730f032d5d446acab73441a709c60331d6cbe

It should fix the issue
`AttributeError: 'SyncForm_t' object has no attribute broker`

**Comment by bootleg** [comment]
> The term listening is very confusing, it should be binding on port XXX and listening on port 9100
> what do you think?

I missed the update. Indeed, I can correct that. Can you confirm that the main bug is fixed ? If so and ok for you I'll close the issue.

**Comment by forker11234** [comment]
I'll check it and update as soon as I can.
Thanks!

**Comment by bootleg** [comment]
Closing the issue as I believe it is fixed. Please reopen if necessary.
